name: Deploy Portfolio

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Inject SMTP Token
        run: |
          sed -i "s/HOST_TOKEN/${{ secrets.HOST_TOKEN }}/g" script.js
          sed -i "s/USER_TOKEN/${{ secrets.USER_TOKEN }}/g" script.js
          sed -i "s/PASS_TOKEN/${{ secrets.PASS_TOKEN }}/g" script.js

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.GH_PAT_TOKEN }}
          branch: gh-pages
          folder: .
